ALTER TABLE users ALTER COLUMN password DROP NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_provider VARCHAR(20) NOT NULL DEFAULT 'LOCAL';
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_subject VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS picture_url VARCHAR(500);
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_google_subject
    ON users (google_subject) WHERE google_subject IS NOT NULL;
