ALTER TABLE cvs
    ADD COLUMN IF NOT EXISTS annee_naissance INTEGER,
    ADD COLUMN IF NOT EXISTS situation_matrimoniale VARCHAR(40),
    ADD COLUMN IF NOT EXISTS sexe VARCHAR(20),
    ADD COLUMN IF NOT EXISTS afficher_infos_sensibles BOOLEAN NOT NULL DEFAULT FALSE;
