import 'country_metadata.dart';

/// Donnees de reference des pays (issue #242) : source unique remplacant les
/// deux listes dupliquees de personal_info_section.dart. Extrait a l'identique
/// de l'ancienne table `_countryDialCodes` (memes noms FR, memes indicatifs).
///
/// Trie par nom FR (ordre d'affichage historique preserve). Ne pas editer a la
/// main : toute evolution passe par une revue de la liste complete.
const List<CountryMetadata> kCountryCatalog = [
  CountryMetadata(id: 'afghanistan', nameFr: 'Afghanistan', dialCode: '+93'),
  CountryMetadata(id: 'afrique du sud', nameFr: 'Afrique du Sud', dialCode: '+27'),
  CountryMetadata(id: 'albanie', nameFr: 'Albanie', dialCode: '+355'),
  CountryMetadata(id: 'algerie', nameFr: 'Algérie', dialCode: '+213'),
  CountryMetadata(id: 'allemagne', nameFr: 'Allemagne', dialCode: '+49'),
  CountryMetadata(id: 'angola', nameFr: 'Angola', dialCode: '+244'),
  CountryMetadata(id: 'arabie saoudite', nameFr: 'Arabie Saoudite', dialCode: '+966'),
  CountryMetadata(id: 'argentine', nameFr: 'Argentine', dialCode: '+54'),
  CountryMetadata(id: 'armenie', nameFr: 'Arménie', dialCode: '+374'),
  CountryMetadata(id: 'australie', nameFr: 'Australie', dialCode: '+61'),
  CountryMetadata(id: 'autriche', nameFr: 'Autriche', dialCode: '+43'),
  CountryMetadata(id: 'azerbaidjan', nameFr: 'Azerbaïdjan', dialCode: '+994'),
  CountryMetadata(id: 'bahrein', nameFr: 'Bahreïn', dialCode: '+973'),
  CountryMetadata(id: 'bangladesh', nameFr: 'Bangladesh', dialCode: '+880'),
  CountryMetadata(id: 'belgique', nameFr: 'Belgique', dialCode: '+32'),
  CountryMetadata(id: 'benin', nameFr: 'Bénin', dialCode: '+229'),
  CountryMetadata(id: 'bielorussie', nameFr: 'Biélorussie', dialCode: '+375'),
  CountryMetadata(id: 'bolivie', nameFr: 'Bolivie', dialCode: '+591'),
  CountryMetadata(id: 'bosnie herzegovine', nameFr: 'Bosnie-Herzégovine', dialCode: '+387'),
  CountryMetadata(id: 'bresil', nameFr: 'Brésil', dialCode: '+55'),
  CountryMetadata(id: 'bulgarie', nameFr: 'Bulgarie', dialCode: '+359'),
  CountryMetadata(id: 'burkina faso', nameFr: 'Burkina Faso', dialCode: '+226'),
  CountryMetadata(id: 'burundi', nameFr: 'Burundi', dialCode: '+257'),
  CountryMetadata(id: 'cambodge', nameFr: 'Cambodge', dialCode: '+855'),
  CountryMetadata(id: 'cameroun', nameFr: 'Cameroun', dialCode: '+237'),
  CountryMetadata(id: 'canada', nameFr: 'Canada', dialCode: '+1'),
  CountryMetadata(id: 'chili', nameFr: 'Chili', dialCode: '+56'),
  CountryMetadata(id: 'chine', nameFr: 'Chine', dialCode: '+86'),
  CountryMetadata(id: 'chypre', nameFr: 'Chypre', dialCode: '+357'),
  CountryMetadata(id: 'colombie', nameFr: 'Colombie', dialCode: '+57'),
  CountryMetadata(id: 'congo', nameFr: 'Congo', dialCode: '+242'),
  CountryMetadata(id: 'coree du sud', nameFr: 'Corée du Sud', dialCode: '+82'),
  CountryMetadata(id: 'costa rica', nameFr: 'Costa Rica', dialCode: '+506'),
  CountryMetadata(id: 'cote d ivoire', nameFr: "Côte d'Ivoire", dialCode: '+225'),
  CountryMetadata(id: 'croatie', nameFr: 'Croatie', dialCode: '+385'),
  CountryMetadata(id: 'cuba', nameFr: 'Cuba', dialCode: '+53'),
  CountryMetadata(id: 'danemark', nameFr: 'Danemark', dialCode: '+45'),
  CountryMetadata(id: 'djibouti', nameFr: 'Djibouti', dialCode: '+253'),
  CountryMetadata(id: 'egypte', nameFr: 'Égypte', dialCode: '+20'),
  CountryMetadata(id: 'emirats arabes unis', nameFr: 'Émirats arabes unis', dialCode: '+971'),
  CountryMetadata(id: 'equateur', nameFr: 'Équateur', dialCode: '+593'),
  CountryMetadata(id: 'espagne', nameFr: 'Espagne', dialCode: '+34'),
  CountryMetadata(id: 'estonie', nameFr: 'Estonie', dialCode: '+372'),
  CountryMetadata(id: 'ethiopie', nameFr: 'Éthiopie', dialCode: '+251'),
  CountryMetadata(id: 'finlande', nameFr: 'Finlande', dialCode: '+358'),
  CountryMetadata(id: 'france', nameFr: 'France', dialCode: '+33'),
  CountryMetadata(id: 'gabon', nameFr: 'Gabon', dialCode: '+241'),
  CountryMetadata(id: 'georgie', nameFr: 'Géorgie', dialCode: '+995'),
  CountryMetadata(id: 'ghana', nameFr: 'Ghana', dialCode: '+233'),
  CountryMetadata(id: 'grece', nameFr: 'Grèce', dialCode: '+30'),
  CountryMetadata(id: 'guatemala', nameFr: 'Guatemala', dialCode: '+502'),
  CountryMetadata(id: 'guinee', nameFr: 'Guinée', dialCode: '+224'),
  CountryMetadata(id: 'haiti', nameFr: 'Haïti', dialCode: '+509'),
  CountryMetadata(id: 'hongrie', nameFr: 'Hongrie', dialCode: '+36'),
  CountryMetadata(id: 'inde', nameFr: 'Inde', dialCode: '+91'),
  CountryMetadata(id: 'indonesie', nameFr: 'Indonésie', dialCode: '+62'),
  CountryMetadata(id: 'irak', nameFr: 'Irak', dialCode: '+964'),
  CountryMetadata(id: 'iran', nameFr: 'Iran', dialCode: '+98'),
  CountryMetadata(id: 'irlande', nameFr: 'Irlande', dialCode: '+353'),
  CountryMetadata(id: 'islande', nameFr: 'Islande', dialCode: '+354'),
  CountryMetadata(id: 'israel', nameFr: 'Israël', dialCode: '+972'),
  CountryMetadata(id: 'italie', nameFr: 'Italie', dialCode: '+39'),
  CountryMetadata(id: 'japon', nameFr: 'Japon', dialCode: '+81'),
  CountryMetadata(id: 'jordanie', nameFr: 'Jordanie', dialCode: '+962'),
  CountryMetadata(id: 'kazakhstan', nameFr: 'Kazakhstan', dialCode: '+7'),
  CountryMetadata(id: 'kenya', nameFr: 'Kenya', dialCode: '+254'),
  CountryMetadata(id: 'kosovo', nameFr: 'Kosovo', dialCode: '+383'),
  CountryMetadata(id: 'koweit', nameFr: 'Koweït', dialCode: '+965'),
  CountryMetadata(id: 'laos', nameFr: 'Laos', dialCode: '+856'),
  CountryMetadata(id: 'lettonie', nameFr: 'Lettonie', dialCode: '+371'),
  CountryMetadata(id: 'liban', nameFr: 'Liban', dialCode: '+961'),
  CountryMetadata(id: 'libye', nameFr: 'Libye', dialCode: '+218'),
  CountryMetadata(id: 'lituanie', nameFr: 'Lituanie', dialCode: '+370'),
  CountryMetadata(id: 'luxembourg', nameFr: 'Luxembourg', dialCode: '+352'),
  CountryMetadata(id: 'madagascar', nameFr: 'Madagascar', dialCode: '+261'),
  CountryMetadata(id: 'malaisie', nameFr: 'Malaisie', dialCode: '+60'),
  CountryMetadata(id: 'mali', nameFr: 'Mali', dialCode: '+223'),
  CountryMetadata(id: 'maroc', nameFr: 'Maroc', dialCode: '+212'),
  CountryMetadata(id: 'maurice', nameFr: 'Maurice', dialCode: '+230'),
  CountryMetadata(id: 'mauritanie', nameFr: 'Mauritanie', dialCode: '+222'),
  CountryMetadata(id: 'mexique', nameFr: 'Mexique', dialCode: '+52'),
  CountryMetadata(id: 'moldova', nameFr: 'Moldova', dialCode: '+373'),
  CountryMetadata(id: 'mongolie', nameFr: 'Mongolie', dialCode: '+976'),
  CountryMetadata(id: 'montenegro', nameFr: 'Monténégro', dialCode: '+382'),
  CountryMetadata(id: 'mozambique', nameFr: 'Mozambique', dialCode: '+258'),
  CountryMetadata(id: 'myanmar', nameFr: 'Myanmar', dialCode: '+95'),
  CountryMetadata(id: 'namibie', nameFr: 'Namibie', dialCode: '+264'),
  CountryMetadata(id: 'nepal', nameFr: 'Népal', dialCode: '+977'),
  CountryMetadata(id: 'nicaragua', nameFr: 'Nicaragua', dialCode: '+505'),
  CountryMetadata(id: 'niger', nameFr: 'Niger', dialCode: '+227'),
  CountryMetadata(id: 'nigeria', nameFr: 'Nigéria', dialCode: '+234'),
  CountryMetadata(id: 'norvege', nameFr: 'Norvège', dialCode: '+47'),
  CountryMetadata(id: 'nouvelle zelande', nameFr: 'Nouvelle-Zélande', dialCode: '+64'),
  CountryMetadata(id: 'oman', nameFr: 'Oman', dialCode: '+968'),
  CountryMetadata(id: 'ouganda', nameFr: 'Ouganda', dialCode: '+256'),
  CountryMetadata(id: 'ouzbekistan', nameFr: 'Ouzbékistan', dialCode: '+998'),
  CountryMetadata(id: 'pakistan', nameFr: 'Pakistan', dialCode: '+92'),
  CountryMetadata(id: 'panama', nameFr: 'Panama', dialCode: '+507'),
  CountryMetadata(id: 'paraguay', nameFr: 'Paraguay', dialCode: '+595'),
  CountryMetadata(id: 'pays bas', nameFr: 'Pays-Bas', dialCode: '+31'),
  CountryMetadata(id: 'perou', nameFr: 'Pérou', dialCode: '+51'),
  CountryMetadata(id: 'philippines', nameFr: 'Philippines', dialCode: '+63'),
  CountryMetadata(id: 'pologne', nameFr: 'Pologne', dialCode: '+48'),
  CountryMetadata(id: 'portugal', nameFr: 'Portugal', dialCode: '+351'),
  CountryMetadata(id: 'qatar', nameFr: 'Qatar', dialCode: '+974'),
  CountryMetadata(id: 'republique tcheque', nameFr: 'République tchèque', dialCode: '+420'),
  CountryMetadata(id: 'roumanie', nameFr: 'Roumanie', dialCode: '+40'),
  CountryMetadata(id: 'royaume uni', nameFr: 'Royaume-Uni', dialCode: '+44'),
  CountryMetadata(id: 'russie', nameFr: 'Russie', dialCode: '+7'),
  CountryMetadata(id: 'rwanda', nameFr: 'Rwanda', dialCode: '+250'),
  CountryMetadata(id: 'senegal', nameFr: 'Sénégal', dialCode: '+221'),
  CountryMetadata(id: 'serbie', nameFr: 'Serbie', dialCode: '+381'),
  CountryMetadata(id: 'sierra leone', nameFr: 'Sierra Leone', dialCode: '+232'),
  CountryMetadata(id: 'singapour', nameFr: 'Singapour', dialCode: '+65'),
  CountryMetadata(id: 'slovaquie', nameFr: 'Slovaquie', dialCode: '+421'),
  CountryMetadata(id: 'slovenie', nameFr: 'Slovénie', dialCode: '+386'),
  CountryMetadata(id: 'somalie', nameFr: 'Somalie', dialCode: '+252'),
  CountryMetadata(id: 'soudan', nameFr: 'Soudan', dialCode: '+249'),
  CountryMetadata(id: 'sri lanka', nameFr: 'Sri Lanka', dialCode: '+94'),
  CountryMetadata(id: 'suede', nameFr: 'Suède', dialCode: '+46'),
  CountryMetadata(id: 'suisse', nameFr: 'Suisse', dialCode: '+41'),
  CountryMetadata(id: 'syrie', nameFr: 'Syrie', dialCode: '+963'),
  CountryMetadata(id: 'taiwan', nameFr: 'Taïwan', dialCode: '+886'),
  CountryMetadata(id: 'tanzanie', nameFr: 'Tanzanie', dialCode: '+255'),
  CountryMetadata(id: 'thailande', nameFr: 'Thaïlande', dialCode: '+66'),
  CountryMetadata(id: 'togo', nameFr: 'Togo', dialCode: '+228'),
  CountryMetadata(id: 'tunisie', nameFr: 'Tunisie', dialCode: '+216'),
  CountryMetadata(id: 'turkmenistan', nameFr: 'Turkménistan', dialCode: '+993'),
  CountryMetadata(id: 'turquie', nameFr: 'Turquie', dialCode: '+90'),
  CountryMetadata(id: 'ukraine', nameFr: 'Ukraine', dialCode: '+380'),
  CountryMetadata(id: 'uruguay', nameFr: 'Uruguay', dialCode: '+598'),
  CountryMetadata(id: 'venezuela', nameFr: 'Venezuela', dialCode: '+58'),
  CountryMetadata(id: 'vietnam', nameFr: 'Vietnam', dialCode: '+84'),
  CountryMetadata(id: 'yemen', nameFr: 'Yémen', dialCode: '+967'),
  CountryMetadata(id: 'zimbabwe', nameFr: 'Zimbabwe', dialCode: '+263'),
];
